# Generated by Django 5.2.17 on 2026-09-03 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('name_az', models.CharField(max_length=60, null=True)),
                ('name_ru', models.CharField(max_length=60, null=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Layihə kateqoriyası',
                'verbose_name_plural': 'Layihə kateqoriyaları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_az', models.CharField(max_length=150, null=True)),
                ('title_ru', models.CharField(max_length=150, null=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('image_url', models.URLField(blank=True)),
                ('meta_primary', models.CharField(blank=True, help_text='Məs. məkan və ya detal', max_length=120)),
                ('meta_primary_az', models.CharField(blank=True, help_text='Məs. məkan və ya detal', max_length=120, null=True)),
                ('meta_primary_ru', models.CharField(blank=True, help_text='Məs. məkan və ya detal', max_length=120, null=True)),
                ('meta_secondary', models.CharField(blank=True, help_text='Məs. qonaq sayı, müddət', max_length=120)),
                ('meta_secondary_az', models.CharField(blank=True, help_text='Məs. qonaq sayı, müddət', max_length=120, null=True)),
                ('meta_secondary_ru', models.CharField(blank=True, help_text='Məs. qonaq sayı, müddət', max_length=120, null=True)),
                ('description', models.TextField(blank=True, help_text='Detal səhifəsi üçün')),
                ('description_az', models.TextField(blank=True, help_text='Detal səhifəsi üçün', null=True)),
                ('description_ru', models.TextField(blank=True, help_text='Detal səhifəsi üçün', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Ana səhifədə göstərilsin')),
                ('gradient_key', models.CharField(choices=[('cool', 'Cool'), ('warm', 'Warm'), ('hot', 'Hot')], default='cool', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectcategory')),
            ],
            options={
                'verbose_name': 'Layihə',
                'verbose_name_plural': 'Layihələr',
                'ordering': ['order', 'id'],
            },
        ),
    ]
