# Generated by Django 5.2.17 on 2026-09-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_meta_description_project_meta_description_az_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_featured', 'order'], name='project_featured_order_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['order', 'id'], name='project_order_idx'),
        ),
    ]
