# Generated by Django 5.2.17 on 2026-09-06 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_project_featured_order_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Şəkil'), ('video', 'Video')], default='image', max_length=8, verbose_name='Növ')),
                ('image', models.ImageField(blank=True, help_text='Video üçün bu, önizləmə (poster) şəkli olur.', upload_to='projects/gallery/', verbose_name='Şəkil')),
                ('image_url', models.URLField(blank=True, verbose_name='Şəkil linki')),
                ('video', models.FileField(blank=True, help_text='MP4', upload_to='projects/video/', verbose_name='Video faylı')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo və ya birbaşa .mp4 linki', verbose_name='Video linki')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Başlıq')),
                ('caption_az', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq')),
                ('caption_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlıq')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project')),
            ],
            options={
                'verbose_name': 'Qalereya elementi',
                'verbose_name_plural': 'Qalereya (şəkil və video)',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['project', 'order'], name='projectmedia_order_idx')],
            },
        ),
    ]
