# Generated by Django 5.2.17 on 2026-09-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('label_az', models.CharField(max_length=80, null=True)),
                ('label_ru', models.CharField(max_length=80, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Xidmət',
                'verbose_name_plural': 'Xidmətlər',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='AS-ART Group', max_length=120)),
                ('site_tagline', models.CharField(blank=True, max_length=255)),
                ('site_tagline_az', models.CharField(blank=True, max_length=255, null=True)),
                ('site_tagline_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_mark_text', models.CharField(default='AS', max_length=10)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_description_az', models.TextField(blank=True, null=True)),
                ('meta_description_ru', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('whatsapp_phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('booking_email', models.EmailField(blank=True, max_length=254)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('address_line_az', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('address_note', models.CharField(blank=True, max_length=255)),
                ('address_note_az', models.CharField(blank=True, max_length=255, null=True)),
                ('address_note_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('working_hours_line', models.CharField(blank=True, max_length=255)),
                ('working_hours_line_az', models.CharField(blank=True, max_length=255, null=True)),
                ('working_hours_line_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('working_hours_note', models.CharField(blank=True, max_length=255)),
                ('working_hours_note_az', models.CharField(blank=True, max_length=255, null=True)),
                ('working_hours_note_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('map_embed_url', models.URLField(blank=True)),
                ('footer_note', models.CharField(blank=True, max_length=255)),
                ('footer_note_az', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_note_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright_text', models.CharField(blank=True, max_length=255)),
                ('copyright_text_az', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright_text_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Sayt tənzimləmələri',
                'verbose_name_plural': 'Sayt tənzimləmələri',
            },
        ),
    ]
