# Generated by Django 5.2.17 on 2026-09-03 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoSettings',
            fields=[
                ('id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('title_suffix', models.CharField(blank=True, default='AS-ART Group', help_text='Səhifə başlığının sonuna əlavə olunur: "Layihələr | AS-ART Group"', max_length=80)),
                ('default_og_image', models.ImageField(blank=True, upload_to='seo/')),
                ('default_og_image_url', models.URLField(blank=True)),
                ('allow_indexing', models.BooleanField(default=False, help_text='Sayt hazır olanda aktivləşdirin. Söndürülü ikən robots.txt bütün axtarış robotlarını bloklayır (hazırlıq mərhələsində indekslənməmək üçün).')),
                ('google_analytics_id', models.CharField(blank=True, help_text='GA4 Measurement ID, məs. G-ABCD123456', max_length=40, validators=[django.core.validators.RegexValidator('^G-[A-Z0-9]{6,12}$', 'GA4 formatı: G-XXXXXXXXXX')])),
                ('google_tag_manager_id', models.CharField(blank=True, help_text='Google Tag Manager ID, məs. GTM-ABC1234 (GA4 ilə birlikdə lazım deyil)', max_length=40, validators=[django.core.validators.RegexValidator('^GTM-[A-Z0-9]{5,10}$', 'GTM formatı: GTM-XXXXXXX')])),
                ('google_site_verification', models.CharField(blank=True, help_text='Google Search Console təsdiq kodu', max_length=120)),
                ('yandex_verification', models.CharField(blank=True, help_text='Yandex Webmaster təsdiq kodu', max_length=120)),
            ],
            options={
                'verbose_name': 'SEO və Analitika',
                'verbose_name_plural': 'SEO və Analitika',
            },
        ),
    ]
