# Generated by Django 5.2.17 on 2026-09-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_query',
            field=models.CharField(blank=True, help_text='Naviqasiya tətbiqlərinə göndərilən ünvan/koordinat. Boş buraxılsa ünvan sətri istifadə olunur.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='office_phone',
            field=models.CharField(blank=True, help_text='Ofis (stasionar) nömrəsi', max_length=32),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, help_text='Əsas mobil nömrə', max_length=32),
        ),
    ]
