# Generated by Django 5.2.17 on 2026-09-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('role', models.CharField(max_length=120)),
                ('role_az', models.CharField(max_length=120, null=True)),
                ('role_ru', models.CharField(max_length=120, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='team/')),
                ('photo_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True, help_text='Detal səhifəsi üçün')),
                ('bio_az', models.TextField(blank=True, help_text='Detal səhifəsi üçün', null=True)),
                ('bio_ru', models.TextField(blank=True, help_text='Detal səhifəsi üçün', null=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Komanda üzvü',
                'verbose_name_plural': 'Komanda üzvləri',
                'ordering': ['order', 'id'],
            },
        ),
    ]
