# Generated by Django 5.2.17 on 2026-09-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
