# Generated by Django 5.2.17 on 2026-09-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_teammember_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Boş buraxılsa bio-dan götürülür', max_length=160),
        ),
        migrations.AddField(
            model_name='teammember',
            name='meta_description_az',
            field=models.CharField(blank=True, help_text='Boş buraxılsa bio-dan götürülür', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='meta_description_ru',
            field=models.CharField(blank=True, help_text='Boş buraxılsa bio-dan götürülür', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Boş buraxılsa ad və vəzifə istifadə olunur', max_length=70),
        ),
        migrations.AddField(
            model_name='teammember',
            name='meta_title_az',
            field=models.CharField(blank=True, help_text='Boş buraxılsa ad və vəzifə istifadə olunur', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='meta_title_ru',
            field=models.CharField(blank=True, help_text='Boş buraxılsa ad və vəzifə istifadə olunur', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
