# Generated by Django 5.2.17 on 2026-09-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_teammember_meta_description_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['order', 'id'], name='team_order_idx'),
        ),
    ]
