# Generated by Django 5.2.17 on 2026-09-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_teammember_team_order_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, help_text='İstəyə bağlı. Boş buraxıla bilər.', max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, help_text='İstəyə bağlı. Boş buraxıla bilər.', max_length=32),
        ),
    ]
