# Generated by Django 5.2.17 on 2026-09-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_teammember_email_teammember_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, help_text='İstəyə bağlı. Boş buraxıla bilər.', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, help_text='İstəyə bağlı. Boş buraxıla bilər.', max_length=32, verbose_name='Telefon'),
        ),
    ]
