# Generated by Django 5.2.17 on 2026-09-03 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(help_text='Məs. "01"', max_length=10)),
                ('tag_label', models.CharField(max_length=60)),
                ('tag_label_az', models.CharField(max_length=60, null=True)),
                ('tag_label_ru', models.CharField(max_length=60, null=True)),
                ('title', models.CharField(max_length=120)),
                ('title_az', models.CharField(max_length=120, null=True)),
                ('title_ru', models.CharField(max_length=120, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_az', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='equipment/')),
                ('image_url', models.URLField(blank=True)),
                ('gradient_key', models.CharField(choices=[('cool', 'Cool'), ('warm', 'Warm'), ('hot', 'Hot')], default='cool', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Avadanlıq kateqoriyası',
                'verbose_name_plural': 'Avadanlıq kateqoriyaları',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('label_az', models.CharField(max_length=60, null=True)),
                ('label_ru', models.CharField(max_length=60, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='equipment.equipmentcategory')),
            ],
            options={
                'verbose_name': 'Avadanlıq etiketi',
                'verbose_name_plural': 'Avadanlıq etiketləri',
                'ordering': ['order', 'id'],
            },
        ),
    ]
