# Generated by Django 5.2.17 on 2026-09-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcategory',
            name='tag_number',
            field=models.CharField(help_text='Məs. "01"', max_length=10, unique=True),
        ),
    ]
