# Generated by Django 5.2.17 on 2026-09-06 17:37

import contact.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_contact_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='PDF, Word və ya Excel — maksimum 10 MB', upload_to='contact/%Y/%m/', validators=[contact.validators.validate_attachment], verbose_name='Əlavə fayl'),
        ),
    ]
