# Generated by Django 5.2.17 on 2026-09-03 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('eyebrow_az', models.CharField(blank=True, max_length=120, null=True)),
                ('eyebrow_ru', models.CharField(blank=True, max_length=120, null=True)),
                ('heading_line1', models.CharField(blank=True, max_length=120)),
                ('heading_line1_az', models.CharField(blank=True, max_length=120, null=True)),
                ('heading_line1_ru', models.CharField(blank=True, max_length=120, null=True)),
                ('heading_line2', models.CharField(blank=True, max_length=120)),
                ('heading_line2_az', models.CharField(blank=True, max_length=120, null=True)),
                ('heading_line2_ru', models.CharField(blank=True, max_length=120, null=True)),
                ('heading_line3', models.CharField(blank=True, max_length=120)),
                ('heading_line3_az', models.CharField(blank=True, max_length=120, null=True)),
                ('heading_line3_ru', models.CharField(blank=True, max_length=120, null=True)),
                ('lead', models.TextField(blank=True)),
                ('lead_az', models.TextField(blank=True, null=True)),
                ('lead_ru', models.TextField(blank=True, null=True)),
                ('cta_primary_label', models.CharField(blank=True, max_length=60)),
                ('cta_primary_label_az', models.CharField(blank=True, max_length=60, null=True)),
                ('cta_primary_label_ru', models.CharField(blank=True, max_length=60, null=True)),
                ('cta_secondary_label', models.CharField(blank=True, max_length=60)),
                ('cta_secondary_label_az', models.CharField(blank=True, max_length=60, null=True)),
                ('cta_secondary_label_ru', models.CharField(blank=True, max_length=60, null=True)),
                ('image', models.ImageField(blank=True, upload_to='home/')),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Hero məzmunu',
                'verbose_name_plural': 'Hero məzmunu',
            },
        ),
        migrations.CreateModel(
            name='HeroFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_key', models.CharField(choices=[('light', 'İşıq'), ('sound', 'Səs'), ('spark', 'Prodakşn')], default='light', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('title_az', models.CharField(max_length=120, null=True)),
                ('title_ru', models.CharField(max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('description_az', models.CharField(blank=True, max_length=255, null=True)),
                ('description_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='home.herocontent')),
            ],
            options={
                'verbose_name': 'Hero xüsusiyyəti',
                'verbose_name_plural': 'Hero xüsusiyyətləri',
                'ordering': ['order', 'id'],
            },
        ),
    ]
