# Generated by Django 5.2.17 on 2026-09-03 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('eyebrow_az', models.CharField(blank=True, max_length=120, null=True)),
                ('eyebrow_ru', models.CharField(blank=True, max_length=120, null=True)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('heading_az', models.CharField(blank=True, max_length=255, null=True)),
                ('heading_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('heading_accent', models.CharField(blank=True, max_length=255)),
                ('heading_accent_az', models.CharField(blank=True, max_length=255, null=True)),
                ('heading_accent_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('lead', models.TextField(blank=True)),
                ('lead_az', models.TextField(blank=True, null=True)),
                ('lead_ru', models.TextField(blank=True, null=True)),
                ('body_paragraph_1', models.TextField(blank=True)),
                ('body_paragraph_1_az', models.TextField(blank=True, null=True)),
                ('body_paragraph_1_ru', models.TextField(blank=True, null=True)),
                ('body_paragraph_2', models.TextField(blank=True)),
                ('body_paragraph_2_az', models.TextField(blank=True, null=True)),
                ('body_paragraph_2_ru', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='about/')),
                ('image_url', models.URLField(blank=True)),
                ('badge_title', models.CharField(blank=True, max_length=120)),
                ('badge_title_az', models.CharField(blank=True, max_length=120, null=True)),
                ('badge_title_ru', models.CharField(blank=True, max_length=120, null=True)),
                ('badge_subtitle', models.CharField(blank=True, max_length=120)),
                ('badge_subtitle_az', models.CharField(blank=True, max_length=120, null=True)),
                ('badge_subtitle_ru', models.CharField(blank=True, max_length=120, null=True)),
                ('cta_primary_label', models.CharField(blank=True, max_length=60)),
                ('cta_primary_label_az', models.CharField(blank=True, max_length=60, null=True)),
                ('cta_primary_label_ru', models.CharField(blank=True, max_length=60, null=True)),
                ('cta_secondary_label', models.CharField(blank=True, max_length=60)),
                ('cta_secondary_label_az', models.CharField(blank=True, max_length=60, null=True)),
                ('cta_secondary_label_ru', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Haqqımızda məzmunu',
                'verbose_name_plural': 'Haqqımızda məzmunu',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('label', models.CharField(max_length=80)),
                ('label_az', models.CharField(max_length=80, null=True)),
                ('label_ru', models.CharField(max_length=80, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('description_az', models.CharField(blank=True, max_length=255, null=True)),
                ('description_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('gradient_key', models.CharField(choices=[('cool', 'Cool'), ('warm', 'Warm'), ('hot', 'Hot')], default='cool', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='about.aboutcontent')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
